name: CMake Linux Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build-linux

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build-linux
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=g++-10

      - name: Build
        working-directory: ${{github.workspace}}/build-linux
        shell: bash
        run: cmake --build . --config $BUILD_TYPE -t kv-api --parallel
      
      - name: Build Tests
        working-directory: ${{github.workspace}}/build-linux
        shell: bash
        run: cmake --build . --config $BUILD_TYPE -t kv-api-tests --parallel

  run-tests:
    needs: linux-build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/download-artifact@master
        with:
          name: kv-api-tests
          path: ${{github.workspace}}
    
      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
            chmod +x ./kv-api-tests
            ./kv-api-tests
